#! /bin/sh -e

cd "$(dirname "$0")"

# This is run on production. The Rails environment is replaced there
RAILS_ENV=development bundle install --deployment
npm install
RAILS_ENV=development ./bin/delayed_job --queue=deployment -n 3 restart
RAILS_ENV=development ./bin/delayed_job --queues=migration,default -n 2 restart
RAILS_ENV=development exec bundle exec puma
