#!/bin/bash -e
export PATH="/root/.rbenv/shims:$PATH"
export PATH="/app/black-knight/bin:$PATH"
cd /app/black-knight/
/root/.rbenv/shims/gem install bundler

# This is run on production. The Rails environment is replaced there
RAILS_ENV=development bundle install --deployment
npm install
RAILS_ENV=development ./bin/delayed_job restart -n 3
RAILS_ENV=development ./bin/rails db:migrate
ln -s /usr/bin/nodejs /usr/bin/node
RAILS_ENV=development exec bundle exec puma

exec "$@"
