development:
  paths: [ stdout, '/app/log/development.log', '/app/storage/logs/laravel.log', '/var/log/nginx/error.log']

production:
  paths: [ stdout, '/app/log/production.log', '/app/storage/logs/laravel.log', '/var/log/nginx/error.log']
